language: php
sudo: false
cache:
    directories:
        - $HOME/.composer/cache/files
        - $HOME/symfony-bridge/.phpunit

env:
    global:
        - PHPUNIT_FLAGS="-v"
        - SYMFONY_PHPUNIT_DIR="$HOME/symfony-bridge/.phpunit"
        # check Symfony versions here https://symfony.com/versions.json
        - SYMFONY_LTS=4.4.*
        - SYMFONY_LATEST=5.2.*
        - SYMFONY_DEV=5.3.*

matrix:
    fast_finish: true
    include:
        - php: 7.2.9
          env: SYMFONY_VERSION=${SYMFONY_LTS}
        - php: 7.3
          env: SYMFONY_VERSION=${SYMFONY_LATEST}
        - php: 7.3
          env: SYMFONY_VERSION=${SYMFONY_DEV}
        - php: 8.0
          env: SYMFONY_VERSION=${SYMFONY_LATEST}
    allow_failures:
        - php: 7.3
          env: SYMFONY_VERSION=${SYMFONY_DEV}

before_install:
    - find ~/.phpenv -name xdebug.ini -delete
    - composer global require --no-progress --no-scripts --no-plugins symfony/flex
    - composer config extra.symfony.require "${SYMFONY_VERSION}"
    - composer config minimum-stability "dev"
    - composer config prefer-stable true
    - composer update

install:
    - ./vendor/bin/simple-phpunit install

script:
    - composer validate --strict --no-check-lock
    - vendor/bin/ecs check src tests --set symfony
    - phpdbg -qrr vendor/bin/phpspec run --no-interaction -f dot
    - vendor/bin/phpstan analyse src --level=max
    - vendor/bin/simple-phpunit $PHPUNIT_FLAGS

notifications:
    email: false
