language: php

cache:
    directories:
        - $HOME/.composer/cache/files
        - $HOME/symfony-bridge/.phpunit
        - SYMFONY_REQUIRE='>=3.4'

env:
    global:
        - PHPUNIT_FLAGS="-v"
        - SYMFONY_PHPUNIT_DIR="$HOME/symfony-bridge/.phpunit"

matrix:
    fast_finish: true
    include:
        -   php: 7.2.9
            env: MARKDOWN_DOCS_TEST_VERSION=stable
        -   php: 7.3
            env: MARKDOWN_DOCS_TEST_VERSION=stable
            # too unstable - sometimes we need other dev deps
            # for things to pass, sometimes dev deps of other libraries
            # are unstable and cause things to fail.
#        - php: 7.3
#          env: MARKDOWN_DOCS_TEST_VERSION=stable-dev
        -   php: 7.3
            env: MARKDOWN_DOCS_TEST_VERSION=dev
        allow_failures:
            -   php: 7.3
                env: MARKDOWN_DOCS_TEST_VERSION=dev

before_install:
        - if [[ $COVERAGE != true ]]; then phpenv config-rm xdebug.ini || true; fi
        - composer global require --no-progress --no-scripts --no-plugins symfony/flex dev-master
        - composer update

install:
    - composer update ${COMPOSER_FLAGS} --prefer-dist --no-interaction
    - ./vendor/bin/simple-phpunit install

script:
    - composer validate --strict --no-check-lock
    - vendor/bin/ecs check src
    - phpdbg -qrr vendor/bin/phpspec run --no-interaction -f dot
    - vendor/bin/phpstan analyse src --level=max
    - vendor/bin/simple-phpunit $PHPUNIT_FLAGS

notifications:
    email: false
