name: Build

env:
    PHPUNIT_FLAGS: "-v"

on:
    push: ~
    pull_request: ~
    release:
        types: [ created ]
    schedule:
        -   cron: "0 1 * * 6" # Run at 1am every Saturday

jobs:
    build:

        runs-on: ubuntu-latest

        name: "PHP ${{ matrix.php }}${{ matrix.symfony != '' && format(', Symfony {0}', matrix.symfony) || '' }}"
        strategy:
            fail-fast: false
            matrix:
                include:
                    -
                        php: 7.4
                        symfony: 4.4.*
                    -
                        php: 7.4
                        symfony: 5.3.*
                    -
                        php: 8.0
                        symfony: 5.4.*
                    -
                        php: 8.0
                        symfony: 6.0.*

        steps:
            -   uses: actions/checkout@v2

            -
                name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: "${{ matrix.php }}"
                    coverage: none

            -
                name: Restrict Symfony version
                if: matrix.symfony != ''
                run: |
                    composer global require --no-progress --no-scripts --no-plugins "symfony/flex"
                    composer config extra.symfony.require "${{ matrix.symfony }}"
                    composer config minimum-stability "dev"
                    composer config prefer-stable true

            -   name: Remove Phpspec
                if: ${{ contains( matrix.symfony, '6.0.*' ) }}
                run: composer remove --dev phpspec/phpspec --no-update

            -
                name: Install dependencies
                run: composer update

            -
                name: Install PHPUnit
                run: vendor/bin/simple-phpunit install

            -
                name: Validate composer.json
                run: composer validate --strict --no-check-lock

            -
                name: Validate coding standard
                run: vendor/bin/ecs check src spec tests

            -
                name: Run phpspec
                if: ${{ true != contains( matrix.symfony, '6.0.*' ) }}
                run: phpdbg -qrr vendor/bin/phpspec run --no-interaction -f dot

            -
                name: Run PHPStan
                run: vendor/bin/phpstan analyse src --level=max

            -
                name: Run Psalm
                run: vendor/bin/psalm

            -
                name: Run PHPUnit
                run: vendor/bin/simple-phpunit $PHPUNIT_FLAGS
