name: PHP Composer

env:
    PHPUNIT_FLAGS: "-v"
    SYMFONY_PHPUNIT_DIR: "$HOME/symfony-bridge/.phpunit"
    SYMFONY_LTS: 4.4.*
    SYMFONY_LATEST: 5.2.*
    SYMFONY_DEV: 5.3.*

on:
    push: ~
    pull_request: ~
    release:
        types: [ created ]
    schedule:
        -   cron: "0 1 * * 6" # Run at 1am every Saturday

jobs:
    build:

        runs-on: ubuntu-latest

        name: "PHP ${{ matrix.php }}${{ matrix.symfony != '' && format(', Symfony {0}', matrix.symfony) || '' }}"
        strategy:
            fail-fast: false
            matrix:
                include:
                    -
                        php: 7.2.9
                        symfony: 4.4.*


        steps:
            -   uses: actions/checkout@v2

            -
                name: Validate composer.json and composer.lock
                run: composer validate --strict
                if: always() && steps.end-of-setup.outcome == 'success'
